name: matrix

on:
  push:

jobs:
  matrix-jobs:
    runs-on: ${{ matrix.runner }}
    strategy: 
      matrix:
        runner: [ubuntu-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]
        include:
          - runner: macos-latest
            python-version: 3.12
        exclude:
          - runner: windows-latest
            python-version: 3.12
    steps:
      - run: echo "This job will run in Python version ${{ matrix.python-version }}"
